-- CREATE TABLE
CREATE TABLE EMPLOYEE (
    id NUMBER,
    ename VARCHAR2(100),
    email VARCHAR2(100),
    gender VARCHAR2(10),
    age NUMBER
);

-- ALTER TABLE (ADD COLUMN)
ALTER TABLE EMPLOYEE ADD city VARCHAR2(50);

-- ALTER TABLE (DROP COLUMN)
ALTER TABLE EMPLOYEE DROP COLUMN city;

-- ALTER TABLE (RENAME COLUMN)
ALTER TABLE EMPLOYEE RENAME COLUMN id TO eid;

-- ALTER TABLE (CHANGE DATA TYPE OF COLUMN)
ALTER TABLE EMPLOYEE MODIFY ename VARCHAR2(50);

-- ALTER TABLE (ADDING CONSTRAINT)
-- specifying constraint name is optional. A default name is given if not provided explicitly.
ALTER TABLE EMPLOYEE ADD CONSTRAINT pk PRIMARY KEY(eid);
ALTER TABLE EMPLOYEE ADD CONSTRAINT unique_email UNIQUE(email);

-- ALTER TABLE (DROPPING CONSTRAINT)
ALTER TABLE EMPLOYEE DROP CONSTRAINT pk;

-- RENAMING THE TABLE
RENAME EMPLOYEE TO EMP;
